### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by MurhafSousli** [ludohenin/ng2-wp-blog#2]
Hey, I'm getting this error when running `build.wp` task, I also want to ask is this project a theme starter or a client app outside the theme directory?

```
src\components\blog\services\wp\terms.ts(27,14): error TS2415: Class 'CategoryModel' incorrectly extends base class 'WpModel'.
  Types of property 'parent' are incompatible.
    Type 'number' is not assignable to type 'WpCollection<WpModel>'.
      Property 'initialized' is missing in type 'Number'.
src\components\blog\services\wp\terms.ts(40,56): error TS2344: Type 'CategoryModel' does not satisfy the constraint 'WpModel'.
```

**Comment by ludohenin** [comment]
@MurhafSousli About the error, this is "just" compiler errors but the code emit with success.

> is this project a theme starter or a client app outside the theme directory

for now an outside app, but I've a plan to make it somewhat a theme as well
