### ISSUE TITLE
Internal link without using href

### ISSUE THREAD

**Issue by hijoncon** [ludohenin/ng2-wp-blog#6]
Very nice demo! Hi do you know how to solve the internal link routing? Example passing [routerLink] looks like it didn't compile.

**Comment by ludohenin** [comment]
@hijoncon I'm not sure what you're trying to do. By internal, you mean link inside a page `#my-heading-somewhere` ? If so, I don't think you can with the Angular router.

**Comment by hijoncon** [comment]
@ludohenin thanks for your reply.  Example in your post usually we use `<a href="some-internal-link">about me</a>` but this will reload the page.  I tried to use `[routerLink]` directive, but it didn't compile...

**Comment by ludohenin** [comment]
Can you provide the error logs ?
